config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  get "pages/home"
  get "pages/dashboard", as: "dashboard"
  get "pages/resumeEditor"
  resources :resumes do
    member do
      get :resume_editor
    end
    resources :jobs
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pages#dashboard"
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :resume
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_resume


  before_action :set_job, only: [ :edit, :update, :destroy ]

  def edit
  end
  def create
    @resume.jobs.create! params.expect(job: [ :title, :company, :location, :summary ])
    redirect_to @resume, notice: "Job was successfully created."
  end

  def destroy
    @resume.jobs.find(params[:id]).destroy!
    redirect_to @resume, status: :see_other, notice: "Job was successfully destroyed."
  end

  def update
    @resume.jobs.find(params[:id]).update! params.require(:job).permit(:title, :company, :location, :summary)
    redirect_to @resume, notice: "Job was successfully updated."
  end

  private
    def set_resume
      @resume = Resume.find(params[:resume_id])
    end

    def set_job
      @job = @resume.jobs.find(params[:id])
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_with model: [@resume,@job] do |form| %>
<% if job.errors.any? %>
<div style="color: red">
    <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

    <ul>
        <% job.errors.each do |error| %>
        <li><%= error.full_message %></li>
        <% end %>
    </ul>
</div>
<% end %>

<div>
    <%= form.label :company, style: "display: block" %>
    <%= form.text_field :company %>
</div>

<div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location %>
</div>

<div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
</div>

<div>
    <%= form.label :summary, style: "display: block" %>
    <%= form.text_field :summary %>
</div>

<div>
    <%= form.submit %>
</div>
<% end %>

app/views/jobs/_job.html.erb
<div id="<%= dom_id(job) %>">
    <%= job.title %><br>
    <%= job.company %><br>
    <%= job.location %><br>
    <%= job.summary %>
    <p>
        <%= link_to "Edit this job", edit_resume_job_path(job.resume,job), class: "link" %>
    </p>
    <%= button_to "Destroy this job", resume_job_path(job.resume,job), method: :delete, class:  %>
</div>

app/views/jobs/_jobs.html.erb
<h3 class="text-lg font-semibold text-gray-700 mb-2">Jobs</h2>

    <div id="jobs">
        <%= render resume.jobs %>
    </div>

    <div data-controller="toggle">
        <button data-toggle-target="button" type="button" data-action="click->toggle#toggle" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
            Add New Job</button>
        <div data-toggle-target="toggleable" class="hidden">
            <h3>New Job:</h3>
            <%= render "jobs/new", resume: resume %>
        </div>

    </div>

app/views/jobs/_new.html.erb
<%= form_with model: [resume, Job.new] do |form| %>
New Job:<br>
<%= form.label :title %><br>
<%= form.text_field :title %><br>
<%= form.label :company %><br>
<%= form.text_area :company %><br>
<%= form.label :location %><br>
<%= form.text_field :location %><br>
<%= form.label :summary %><br>
<%= form.text_field :summary %><br>
<%= form.submit "Create Job" %>

<% end %>
<button data-action="click->toggle#toggle">Cancel</button>

app/views/jobs/edit.html.erb
<% content_for :title, "Editing Job" %>

<h1>Editing job:</h1>

<%= render "form", job: @job %>

<br>

<div>
    <%= link_to "Back to resume", resume_path(@resume.id), class: "link" %>
</div>