config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  get "pages/home"
  get "pages/dashboard", as: "dashboard"
  get "pages/resumeEditor"
  resources :resumes do
    member do
      get :resume_editor
    end
    resources :jobs
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pages#dashboard"
end

app/models/resume.rb
class Resume < ApplicationRecord
  belongs_to :user
  has_many :jobs, dependent: :destroy
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :set_resume, only: %i[ show edit update destroy resume_editor ]

  # GET /resumes or /resumes.json
  def index
    @resumes = Current.user.resumes
  end

  # GET /resumes/1 or /resumes/1.json
  def show
  end

  # GET /resumes/new
  def new
    @resume = Resume.new
  end

  # GET /resumes/1/edit
  def edit
  end

  # POST /resumes or /resumes.json
  def create
    @resume = Current.user.resumes.build(resume_params)

    respond_to do |format|
      if @resume.save
        format.html { redirect_to @resume, notice: "Resume was successfully created." }
        format.json { render :show, status: :created, location: @resume }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resumes/1 or /resumes/1.json
  def update
    respond_to do |format|
      if @resume.update(resume_params)
        format.html { redirect_to @resume, notice: "Resume was successfully updated." }
        format.json do
          preview_html = render_to_string(partial: "resumes/resume", locals: { resume: @resume }, formats: [ :html ])
          render json: { message: "Saved", resume: @resume, previewHtml: preview_html }, status: :ok
        end
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resumes/1 or /resumes/1.json
  def destroy
    @resume.destroy!

    respond_to do |format|
      format.html { redirect_to resumes_path, status: :see_other, notice: "Resume was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def resume_editor
    @resume
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resume
      @resume = Current.user.resumes.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def resume_params
      params.expect(resume: [ :name, :email, :phone, :summary, :title  ])
    end
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/views/resumes/_form.html.erb
<%= form_with(model: resume) do |form| %>
<% if resume.errors.any? %>
<div style="color: red">
    <h2><%= pluralize(resume.errors.count, "error") %> prohibited this resume from being saved:</h2>

    <ul>
        <% resume.errors.each do |error| %>
        <li><%= error.full_message %></li>
        <% end %>
    </ul>
</div>
<% end %>
<div data-autosave-target="form">
    <div>
        <%= form.label :title, style: "display: block" %>
        <%= form.text_field :title %>
    </div>

    <div>
        <%= form.label :name, style: "display: block" %>
        <%= form.text_field :name %>
    </div>

    <div>
        <%= form.label :email, style: "display: block" %>
        <%= form.text_field :email %>
    </div>

    <div>
        <%= form.label :phone, style: "display: block" %>
        <%= form.text_field :phone %>
    </div>

    <div>
        <%= form.label :summary, style: "display: block" %>
        <%= form.text_field :summary %>
    </div>

    <div>
        <%= form.submit %>
    </div>
</div>
<% end %>

app/views/resumes/_index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Resumes" %>


<div id="resumes">
    <% @resumes.each do |resume| %>
    <li class="bg-white shadow-md rounded-md p-4 flex justify-between items-center">

        <p class="text-blue-500"><%= resume.title %></p>
        <div>
            <%= link_to "View", resume, class: "text-green-500 hover:underline"%>
        </div>


    </li>
    <% end %>
</div>

<%= link_to "Create New Resume", new_resume_path, class: "bg-blue-500 hover:bg-blue-700 text_white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>

app/views/resumes/_preview.html.erb
<div>
    <%= render @resume%>
</div>

app/views/resumes/_resume.html.erb
<div id="<%= dom_id resume %>">

    <div class="mb-6 border-b pb-4">
        <div class="text-2xl font-bold text-gray-800 mb-1"><%= resume.name %>
            <div class="text-gray-600 text-sm"><%=resume.email%> | <%= resume.phone%>
            </div>

        </div>

    </div>

app/views/resumes/_resume_editor_form.html.erb
<%= form_with(model: resume, data: { action: "input->autosave#save", autosave_target: "form"}) do |form| %>
<% if resume.errors.any? %>
<div style="color: red">
    <h2><%= pluralize(resume.errors.count, "error") %> prohibited this resume from being saved:</h2>

    <ul>
        <% resume.errors.each do |error| %>
        <li><%= error.full_message %></li>
        <% end %>
    </ul>
</div>
<% end %>
<div data-autosave-target="form">
    <div class="mb-4">
        <%= form.label :title, class: "block text-gray-700 text-sm font-bold mb-2"%>
        <%= form.text_field :title, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    </div>

    <div class="mb-4">
        <%= form.label :name, class: "block text-gray-700 text-sm font-bold mb-2"%>
        <%= form.text_field :name, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    </div>

    <div class="mb-4">
        <%= form.label :email, class: "block text-gray-700 text-sm font-bold mb-2"%>
        <%= form.text_field :email, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    </div>

    <div class="mb-4">
        <%= form.label :phone, class: "block text-gray-700 text-sm font-bold mb-2"%>
        <%= form.text_field :phone, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    </div>

    <div class="mb-4">
        <%= form.label :summary, class: "block text-gray-700 text-sm font-bold mb-2"%>
        <%= form.text_field :summary, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    </div>
</div>
<% end %>

app/views/resumes/_resume_list_item.html.erb
<div id="<%= dom_id resume %>">

    <p>
        <%= resume.title %>
    </p>

    <p>
        <%= resume.name %>
    </p>

    <p>
        <%= resume.email %>
    </p>

    <p>
        <%= resume.phone %>
    </p>

    <p>
        <%= resume.summary %>
    </p>

</div>

app/views/resumes/edit.html.erb
<% content_for :title, "Editing resume" %>

<h1>Editing resume</h1>

<%= render "form", resume: @resume %>

<br>

<div>
    <%= link_to "Back to resume", @resume, class: "link" %>
</div>

app/views/resumes/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Resumes" %>

<h1>Resumes</h1>

<div id="resumes">
    <% @resumes.each do |resume| %>
    <%= render resume %>
    <p>
        <%= link_to "Show this resume", resume, class: "link" %>
    </p>
    <% end %>
</div>

<%= link_to "New resume", new_resume_path %>

app/views/resumes/new.html.erb
<% content_for :title, "New resume" %>

<h1>New resume</h1>

<%= render "form", resume: @resume %>

<br>

<div>
  <%= link_to "Back to resumes", resumes_path %>
</div>

app/views/resumes/resume_editor.html.erb
<div class=" mx-auto bg-white shadow-md rounded-md p-8" data-controller="autosave">
    <h1 class="text-2xl font-semibold mb-6 text-gray-700">Resume Editor</h1>
    <div class="grid grid-cols-2 gap-4">

        <div class="grid grid-cols-1 md:grid-cols-2 gap-8">

            <%= render "resume_editor_form", resume: @resume %>
        </div>

        <div class="bg-white rounded-md p-6 border border-gray-200" data-autosave-target="preview">

            <%= render "resumes/resume", resume: @resume %>
        </div>
    </div>
</div>

app/views/resumes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @resume %>

<div class="mt-6">
    <div class="flex items-center space-x-4 mb-2">
        <%= link_to "Edit", resume_editor_resume_path, class: "bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
        <%= button_to "Delete", @resume, method: :delete, class: "bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
    </div>
    <%= link_to "Back to resumes", dashboard_path, class: "text-blue-500 hover:underline" %>

    <%= render "jobs/jobs", resume: @resume%>
</div>